development:
  cloud_name: <%= ENV["cloudinary_name"] %>
  api_key: <%= ENV["cloudinary_api_key"] %>
  api_secret: <%= ENV["cloudinary_api_secret"] %>

production:
  cloud_name: <%= ENV["cloudinary_name"] %>
  api_key: <%= ENV["cloudinary_api_key"] %>
  api_secret: <%= ENV["cloudinary_api_secret"] %>